{{- $virtualhost := index (pick .Values.Project.virtualhost .EnvFiles.Config.ENV) .EnvFiles.Config.ENV -}}
version: '3.3'


services:


  toolbox:
    image: gulnap/kickoff-docker-php-images:toolbox-3.6-v2.2.0
    container_name: {{ .EnvFiles.Config.ENV }}-{{ .Values.Project.name }}-toolbox
    networks:
      - backend
    environment:
      - VIRTUAL_HOST={{ $virtualhost }}
      - ENV={{ .EnvFiles.Config.ENV }}
      - TRAEFIK_USER={{ .Values.Modules.traefik.user }}
      - TRAEFIK_PASSWORD={{ .EnvFiles.Config.TRAEFIK_PASSWORD }}
      - GRAYLOG_ROOT_PASSWORD_SHA2={{ .EnvFiles.Config.GRAYLOG_PASSWORD }}
      - GRAYLOG_ENABLED={{ .Values.Modules.graylog.enable }}
    labels:
      - traefik.enable=false
    volumes:
      - ./generated:/generated:rw
      - ./scripts:/scripts:ro


networks:


  backend:
    driver: bridge