# |--------------------------------------------------------------------------
# | PHP application cross-environments configuration variables
# |--------------------------------------------------------------------------
# |
# | You can add here variables which are useful to configure your PHP
# | application.
# |
# | Of course, you should update the Orbit file located at
# | 'config/orbit/orbit-build.yml' to add a command which uses those values.
# |